version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: livros_app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=livros
      - DB_PORT=5432
    networks:
      - livros-network
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: livros_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livros
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - livros-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d livros"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  livros-network:
    driver: bridge

volumes:
  postgres_data:

