version: '3'
services:
  db:
    image: postgres:latest
    container_name: livros_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=livros
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      
