version: '3'
services:
  app:
    build: .
    container_name: livros_app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
  
  db:
    image: postgres:latest
    container_name: livros_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=livros
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d livros"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
      
